### ISSUE TITLE
need to update the tutorial

### ISSUE THREAD

**Issue by TianshuDing** [ailidani/paxi#9]
In HOW TO RUN, the 3 step is not working. Because the ./client -h tell me there is no -bconfig, and there is no 'benchmark.json'.

**Comment by ailidani** [comment]
Thanks for letting me know. I previously merged the benchmark config into the [config.json](https://github.com/ailidani/paxi/blob/768848a3ef106ab25535871d2ea864796b8dfa29/bin/config.json#L30) file, but forgot to update the doc.

**Comment by TianshuDing** [comment]
So, if i want to set more node in the network to test the throughput, what i need to do?
Just change the config.json file?

**Comment by ailidani** [comment]
The default config file throttle throughput at 1000, to compare the latency.
"Throttle": 1000,

if you set this to 0, then client will benchmark at the highest possible throughput for the concurrency level (default to 1).
"Concurrency": 1,

For pushing the limit of throughput, you need to try and test the best Concurrency suitable for your hardware limit. (start around 20 and increase)

**Comment by TianshuDing** [comment]
thank you for reply, i have already figure it out, same as u say. and i add a random latency by using TC command.
Have you considered specifying the core when starting a program on a multi-core machine, so every server have the same source.
(using the taskset command)
